name: myelomarisk
description: An application that showcases the prognosis of different stages of MM based on user input.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.5


  english_words: ^4.0.0
  provider: ^6.1.2
  video_player: ^2.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

  flutter_launcher_icons: "^0.13.1"

flutter_icons:
  image_path: "assets/unnamed.png"
  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true
  assets:
    - web/assets/VincentRajkumar.jpg
    - web/assets/AmadouToure.JPG
    - web/assets/ShajiKumar.jpg
    - web/assets/national-cancer-institute-L7en7Lb-Ovc-unsplash.jpeg
    - web/assets/combined_video.mp4
